# Generated by Django 6.1.1 on 2026-09-19 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('achievement_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('name', models.CharField(max_length=150)),
                ('issuing_organization', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('school_name', models.CharField(max_length=150)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('field_of_study', models.CharField(blank=True, max_length=100)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, help_text='e.g. Ongoing, Graduated', max_length=30)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('company_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Leave empty if current', null=True)),
                ('employment_status', models.CharField(blank=True, help_text='e.g. Full-time, Internship, Freelance', max_length=30)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g. Full-Stack Developer', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('cv_url', models.URLField(blank=True, max_length=500)),
                ('available_for_work', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, help_text='e.g. Full Stack, School Project', max_length=100)),
                ('tech_stack', models.CharField(blank=True, help_text='Comma separated: React, Django, PostgreSQL', max_length=255)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('click_behavior', models.CharField(choices=[('case_study', 'Open case study page'), ('external', 'Open external link directly')], default='case_study', max_length=20)),
                ('live_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('extra_link_label', models.CharField(blank=True, max_length=50)),
                ('extra_link_url', models.URLField(blank=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('challenges', models.TextField(blank=True)),
                ('lessons', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, help_text='e.g. Frontend, Backend, Database, Tools', max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('years', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
