# Generated by Django 6.1.1 on 2026-09-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_profile_github_url_alter_profile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='certification',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
