# Generated by Django 6.1.1 on 2026-09-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_achievement_image_url_certification_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_quote',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_learning',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
